### ISSUE TITLE
[Request]: Mod-10

### ISSUE THREAD

**Issue by bdsumon4u** [asifur-rahman1/Share#1]
Vaiya, `Mod-10` ta koren please.

**Comment by asif17r** [comment]
dur bai. ami akta solve kortsi na.. ami just ak pc theke arek pc te nawar jonno.

**Comment by asif17r** [comment]
ami aita private kore dibo daraw

**Comment by bdsumon4u** [comment]
**Please** vaiya, `Mod-10` ta kor. Ami 2 din tirai korsi, pari nai.

**Comment by asifur-rahman1** [comment]
```

**Comment by asifur-rahman1** [comment]
```

**Comment by asif17r** [comment]
```
module mod10_counter(q, q_bar, clear, clk);
  
	input clk, clear;
	output [3:0] q, q_bar;
	nand(clear, q[1], q[3]);
	jk_flip_flop jk1(q[0], q_bar[0], 1, 1, clear, clk);
	jk_flip_flop jk2(q[1], q_bar[1], 1, 1, clear, q[0]);
	jk_flip_flop jk3(q[2], q_bar[2], 1, 1, clear, q[1]);
	jk_flip_flop jk4(q[3], q_bar[3], 1, 1, clear, q[2]);
  
endmodule


module jk_flip_flop(q, q_bar, j, k, clear, clk);
  
	input j, k, clear, clk;
	output q, q_bar;
	wire a, b, c, d, e, f;
	nand(a, q_bar, j, clk, clear);
	nand(b, k, clk, q);
	nand(c, a, d);
	nand(d, c, clear, b);
	not(clk_bar, clk);
	nand(e, c, clk_bar);
	nand(f, d, clk_bar);
	nand(q, e, q_bar);
	nand(q_bar, q, clear, f);
  
endmodule
```
Aita code .

**Comment by asif17r** [comment]
kintu khahini ase.. 
1st a 1ps er jonno clear ar value 0 force korte hbe (deposit option )
then time age moto 100ps set kore 1 value force korte hbe (deposite)
tahole tik moto kaj korbe.. simulation

**Comment by bdsumon4u** [comment]
> Aita code .

As far as I remember, exact same thing e korsilam.
But `1010` te reset hoi nai amar. `0000` -> `1111` count kortesilo.

**Comment by asif17r** [comment]
remember er kheta mari.
ami code dawar age simulate kore dekhsi

**Comment by Rafat-Hossain-Reyal** [comment]
Oi modon taratari mod 10 ta valovabe solve kor naile Tor hardware lab sob vul val output dekhabe

**Comment by bdsumon4u** [comment]
> then time age moto 100ps set kore 1 value force korte hbe (deposite)

Na korleo hoitese.
